name: control_impresoras
description: "Este es un proyecto que se desarrollo especificamente para la empresa de tokai de mexico , Donde la finalidad de esto es optimizar y tener mas eficiencia con las impreosoras CRUD de impresoras y tóner."
publish_to: 'none'

# Para más información sobre cómo configurar tu proyecto, visita:
# https://flutter.dev/docs/development/packages-and-plugins/developing-packages
version: 1.14.5+1

environment:
  sdk: ">=3.0.0 <4.0.0"

# Dependencias principales
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  drift: ^2.7.0
  drift_flutter: ^0.2.4
  path_provider: ^2.0.14
  excel: ^4.0.6
  path: ^1.9.1
  sqlite3_flutter_libs: ^0.5.8
  file_picker: ^5.5.0
  open_file: ^3.3.3
  sqflite: ^2.4.2
  logger: ^2.5.0
  collection: ^1.17.2
  intl: ^0.19.0
  table_calendar: ^3.0.9

  flutter_localizations:
    sdk: flutter
  fl_chart: ^1.0.0







# Herramientas de desarrollo para generación de código y pruebas
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0
  drift_dev: ^2.7.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_tokai.png
